### ISSUE TITLE
Falso positive when package name and lib name differ

### ISSUE THREAD

**Issue by mkatychev** [bnjbvr/cargo-machete#111]
Any dependency where the package name is different from the lib name (`use pkg::*;`) is marked as a false positive, this seems to be consistent across the board:

```toml
[package]
name = "package"

[lib]
name = "pkg"
path = "src/lib.rs"
```
```
$ cargo machete --version
0.6.1
```

Example:
https://github.com/maciejhirsz/tiny-bip39/blob/master/Cargo.toml#L1-L19

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Does it work if you run `cargo-machete --with-metadata`? this will look for crate renamings like this one, if I remember correctly.

**Comment by mkatychev** [comment]
Thanks for the help @bnjbvr that does ameliorate it!

**Comment by mkatychev** [comment]
It would be nice if there was an option to whitelist dependencies for generated code:

```toml
[dependencies]
prost-types.workspace = true

[build-dependencies]
prost-types.workspace = true
```

`prost-types` gets flagged in this case because the generated code gets sent to `OUT_DIR`. I'm assuming scanning rust code generated by `build.rs` in `OUT_DIR` is a bit of a lift right now though.
