### ISSUE TITLE
Add a `*.metadata.cargo-machete.renamed` field to configure renamed crates

### ISSUE THREAD

**Issue by jalil-salame** [bnjbvr/cargo-machete#152]
Having an explicit renamed field should help with false positives without using `--with-metadata`, in my employer's codebase we see more false positives with `--with-metadata`.

I would be willing to code this feature.

Example:

```toml
[package.metadata.cargo-machete.renamed]
# crate-name = "import-name"
rustls-webpki = "webpki"
```
