### ISSUE TITLE
Github Actions fails with "feature `edition2024` is required"

### ISSUE THREAD

**Issue by Hofer-Julian** [bnjbvr/cargo-machete#158]
At the moment, GitHub Actions fails with the following error message:

```
error: failed to download `cargo-machete v0.8.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-machete-0.8.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.84.0 (66221abde 2024-11-19)).
```

https://github.com/prefix-dev/pixi/actions/runs/13521794879/job/37782528425?pr=3207

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Sorry about all the breakage, I didn't imagine that bumping the project would break the project being run in CI.

There's a solution explained in https://github.com/bnjbvr/cargo-machete/issues/156#issuecomment-2681308436 that I'll copy here, for exposure:

I've now hardcoded the release version in the Github action. I've also pushed a tag for v0.7.1 that includes the hardcoded version 0.7.0 in the Github action.

This way, you can choose:

- either the `main` version of the github action, which is using 0.8.0, if you've updated your project to Rust 2024,
- or the `v0.7.1` version of the github action, which is using 0.7.0, if you haven't updated yet to Rust 2024

Example of using the `v0.7.1` version:

```yaml
name: Cargo Machete
on:
  pull_request: { branches: "*" }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@v0.7.1
```

**Comment by MrCroxx** [comment]
Met the same problem.

Instead of installing a old cargo-machete version, you can also install the rust toolchain >= 1.85.0 for the Github hosted runner, whose default rust-toolchain version is 1.84.0 (at 2025-02-27).

e.g.

```yaml
  rust-machete:
    name: rust machete check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run cargo machete
        uses: bnjbvr/cargo-machete@main

```
