### ISSUE TITLE
The result of cargo machete is wrong when using macro from other crate.

### ISSUE THREAD

**Issue by RinChanNOWWW** [bnjbvr/cargo-machete#61]
Crate A:

```rust
#[macro_export]
macro_rules! a_macro {
    crate_c::macro(xxx)
}
```

Crate A's Cargo.toml:

```toml
[dependencies]
create_c = "xxx"
```

Crate B:

```rust
// use a_macro
a_macro();
```

Crate B's Cargo.toml:

```toml
[dependencies]
crate_a = "xxx"
crate_c = "xxx"
```

Machete thinks crate C is not used in crate B.

But only if we make crate C as a dependency of crate B can we compile crate B.
