### ISSUE TITLE
False positives when indirect dependency is used for enabling features

### ISSUE THREAD

**Issue by bonsairobo** [bnjbvr/cargo-machete#68]
For example, I have a repo that depends on `parry3d-f64`, which does not expose the `glam` conversion feature. But I am able to enable this feature by adding the `nalgebra` dependency like this:

```toml
nalgebra = { version = "0.32", features = ["convert-glam022"] }
parry3d-f64 = { version = "0.13" }
```

`cargo machete` will return a false positive for `nalgebra` because I am not `use`ing it anywhere, but it is nonetheless still a necessary dependency.
