### ISSUE TITLE
Set up a Github Action that people can plain use in their projects

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/cargo-machete#73]
Probably the Github action could download the binary from the latest release, and then run machete. Maybe the action would have some parameters that are equivalent to the CLI flags and parameters.

Contributions would be appreciated :)

**Comment by parasyte** [comment]
FWIW, I'm currently using this for my CI pipelines to ensure the app is cached/avoid rebuilds on every run:

```yaml
  - name: Install cargo-machete
    uses: baptiste0928/cargo-install@v2
    with:
      crate: cargo-machete
  - name: Cargo machete
    run: cargo machete
```

**Comment by tgnottingham** [comment]
I've also added support for cargo-machete to https://github.com/taiki-e/install-action.

```yaml
  - uses: taiki-e/install-action@v2
    with:
      tool: cargo-machete

  - uses: actions-rs/cargo@v1
    with:
      command: machete
```
