### ISSUE TITLE
actions-rs/cargo@v1 use Node12. Please update the following actions to use Node.js 16

### ISSUE THREAD

**Issue by istellino-chub** [bnjbvr/cargo-machete#98]
Hello there,
This action is using Node12 which is deprecated
https://github.com/bnjbvr/cargo-machete/blob/881ee93cb16f717244d963d9c46f2fd3884048bb/action.yml#L11C29-L11C29 .
Would you consider to replace it with another option like https://github.com/clechasseur/rs-cargo ?

**Comment by bnjbvr** [comment]
Hi! Not sure, is it a problem that CI's using an old version of Node? This action was just a cache for the binary I suppose, happy to use anything else that'd be as simple and well maintained.

**Comment by istellino-chub** [comment]
For example if I add this to a git workflow:
```
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Machete
        uses: bnjbvr/cargo-machete@main
```
I will get this warning
`The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/cargo@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`
